### ISSUE TITLE
this library is only for russians?

### ISSUE THREAD

**Issue by atesin** [GyverLibs/Random16#1]
hi... please post documentation in english

i am not an u.s. citizen, i don't like u.s.a. so much too... i am chilean and speak spanish

but unfortunately currently there are more people around the world that speaks english than russian (same with spanish)...  so if you want your library be more popular in THE WORLD (not only in u.s.a.) i think you should post your library in english

i would like to know what is all about, but i don't understand a word!

thanks

**Comment by GyverLibs** [comment]
Hello, use Google translate

**Comment by atesin** [comment]
hi....  paste this link in readme.md

https://github-com.translate.goog/GyverLibs/Random16?_x_tr_sl=ru&_x_tr_tl=en

**Comment by GyverLibs** [comment]
Nice, thanks
